/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as ApiBookmarksSyncRouteImport } from './routes/api/bookmarks/sync'
import { Route as ApiBookmarksMetadataRouteImport } from './routes/api/bookmarks/metadata'
import { Route as ApiBookmarksAiTagsRouteImport } from './routes/api/bookmarks/ai-tags'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksSyncRoute = ApiBookmarksSyncRouteImport.update({
  id: '/api/bookmarks/sync',
  path: '/api/bookmarks/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksMetadataRoute = ApiBookmarksMetadataRouteImport.update({
  id: '/api/bookmarks/metadata',
  path: '/api/bookmarks/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookmarksAiTagsRoute = ApiBookmarksAiTagsRouteImport.update({
  id: '/api/bookmarks/ai-tags',
  path: '/api/bookmarks/ai-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ai-tags': typeof ApiBookmarksAiTagsRoute
  '/api/bookmarks/metadata': typeof ApiBookmarksMetadataRoute
  '/api/bookmarks/sync': typeof ApiBookmarksSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ai-tags': typeof ApiBookmarksAiTagsRoute
  '/api/bookmarks/metadata': typeof ApiBookmarksMetadataRoute
  '/api/bookmarks/sync': typeof ApiBookmarksSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_layout': typeof authLayoutRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bookmarks/ai-tags': typeof ApiBookmarksAiTagsRoute
  '/api/bookmarks/metadata': typeof ApiBookmarksMetadataRoute
  '/api/bookmarks/sync': typeof ApiBookmarksSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/bookmarks/ai-tags'
    | '/api/bookmarks/metadata'
    | '/api/bookmarks/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/bookmarks/ai-tags'
    | '/api/bookmarks/metadata'
    | '/api/bookmarks/sync'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_layout'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/api/auth/$'
    | '/api/bookmarks/ai-tags'
    | '/api/bookmarks/metadata'
    | '/api/bookmarks/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBookmarksAiTagsRoute: typeof ApiBookmarksAiTagsRoute
  ApiBookmarksMetadataRoute: typeof ApiBookmarksMetadataRoute
  ApiBookmarksSyncRoute: typeof ApiBookmarksSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/sync': {
      id: '/api/bookmarks/sync'
      path: '/api/bookmarks/sync'
      fullPath: '/api/bookmarks/sync'
      preLoaderRoute: typeof ApiBookmarksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/metadata': {
      id: '/api/bookmarks/metadata'
      path: '/api/bookmarks/metadata'
      fullPath: '/api/bookmarks/metadata'
      preLoaderRoute: typeof ApiBookmarksMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookmarks/ai-tags': {
      id: '/api/bookmarks/ai-tags'
      path: '/api/bookmarks/ai-tags'
      fullPath: '/api/bookmarks/ai-tags'
      preLoaderRoute: typeof ApiBookmarksAiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBookmarksAiTagsRoute: ApiBookmarksAiTagsRoute,
  ApiBookmarksMetadataRoute: ApiBookmarksMetadataRoute,
  ApiBookmarksSyncRoute: ApiBookmarksSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
